apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustereye-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustereye-api
  template:
    metadata:
      labels:
        app: clustereye-api
    spec:
      containers:
      - name: clustereye-api
        image: your-registry/clustereye-api:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50051
          name: grpc
        env:
        # Database configuration via environment variables
        - name: DB_HOST
          value: "postgres-service"  # Replace with your PostgreSQL service name
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_NAME
          value: "clustereye"
        - name: DB_SSLMODE
          value: "disable"

        # InfluxDB configuration via environment variables
        - name: INFLUXDB_ENABLED
          value: "true"
        - name: INFLUXDB_URL
          value: "http://influxdb-service:8086"  # Replace with your InfluxDB service name
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-secret
              key: token
        - name: INFLUXDB_ORG
          value: "clustereye"
        - name: INFLUXDB_BUCKET
          value: "clustereye"

        # Optional: Enable debug mode for troubleshooting
        - name: DEBUG_MODE
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: clustereye-api-service
spec:
  selector:
    app: clustereye-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 50051
    targetPort: 50051
  type: ClusterIP

---
# Example secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  password: RGtqZjMzNHV0cmUx  # Base64 encoded "Dkjf334utre1"

---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
data:
  token: dTIwTk1vbU83U3ExcFUxM0JSVDBwUFQ2a245cVQzRC1wRnA3bVZndlJrRHN3bEdpY0Y0b0szUGJiSVY5Vzk2S3dJSVUteG9pTjJCT3pwbGZMczdaanc9PQ==  # Base64 encoded token