server:
  name: ClusterEye
grpc:
  address: :50051
http:
  address: :8080

log:
  level: info          # debug, info, warn, error
  format: json         # json, text
  output: both         # console, file, both
  file_path: logs/clustereye.log
  max_size: 100        # MB
  max_backups: 5       # backup dosya sayısı
  max_age: 30          # gün
  compress: true       # eski dosyaları sıkıştır

database:
  host: clustereye-stack-postgresql
  port: 5432
  user: postgres
  password: Dkjf334utre1
  dbname: clustereye
  sslmode: disable

influxdb:
  enabled: true
  url: "http://clustereye-stack-influxdb:8086"
  token: "clustereye-token"
  organization: "clustereye"
  bucket: "clustereye"
  batch_size: 1000
  flush_interval: 10
